server:
    port: 8814
spring:
    profiles:
        active: @activeProfile@
seata:
    enabled: true
    application-id: seata-user-server
    tx-service-group: my_test_tx_group
    config:
        type: nacos
        file:
            name: file.conf
        nacos:
            namespace:
            serverAddr: 127.0.0.1:8848
            group: SEATA_GROUP
            userName: ""
            password: ""
    registry:
        type: nacos
        nacos:
            application: seata-server
            server-addr: 127.0.0.1:8848
            namespace:
            userName: ""
            password: ""
